- b2
I made this a separate request mostly to limit the size of the next one
> Preparation for upload file refactor

- b2
- test_b2_command_line.py
> Sync tests

- b2
- test_b2_command_line.py
Takes care of some TODO items in the code.
> Refactor upload in sync.

- b2
Also add a suppression for flake8 to ignore pyflakes alert about redefinition of imported module
> tqdm inheritance fix

- b2
This PR relies on the changes from #33, so please do not merge before #33 is merged.
> Implement Bucket.list_file_names() and Bucket.list_file_versions()

- b2
found here: https://www.backblaze.com/b2/docs/b2_upload_file.html
> Add StorageCapExceeded exception

- b2
> Correct some issues reported by pyflakes

- b2
This is a proposal for a "raw API" layer underneath the B2Api class.  The idea is to have a super-simple HTTP wrapper class that doesn't need much testing itself, and can be replaced with a mock or simulator class for testing the layers of code above it.
> Raw api layer

- README.md
- contrib/b2
> Added a bash completion script

- b2
Thanks to Pawel for the useful comments.
> Second try at moving bucket-related calls to B2RawApi.

- b2/b2.py
At Backblaze, we'd like to know which requests are coming from
this tool/library.
> Add a custom user-agent string.

- b2/b2.py
json.load() doesn't work on http responses in
python 3.  this change adds explicit encoding
and decoding where needed.
> Workarounds for Python 3 json/str/bytes issues.

- b2/b2.py
This is in preparation for unit tests.  The next step will be to build a stub/simulator for B2RawApi that the unit tests can use.
> Finish moving all API calls into B2RawApi.

- .travis.yml
- README.md
- b2/__init__.py
- b2/b2.py
- pre-commit.sh
- test/test_sync.py
The new code is not used yet, but I think it's a good time to merge.
I'm working towards a sync implementation that can be multi-threaded, and that has clean layering so that it's testable.  The work so far includes folder classes (local and B2) that have a common interface, and a `make_sync_folder_sync_actions` function that figures out what needs to happen to get two folders in sync.
> Initial work on a unit-testable version of the sync command.

- b2/b2.py
- b2/raw_simulator.py
- pre-commit.sh
- test/test_bucket.py
This is not useful yet, but it does sketch out the design I have in mind.  It seems like a good time to put it out for comments, before I get in too deep.
> Start work on unit tests for Bucket.ls()

- .travis.yml
- Makefile
- README.md
- b2/__main__.py
- b2/b2.py
- b2/progress.py
- pre-commit.sh
- test_b2_command_line.py
Start getting ready to implement large file support.  The first step will be to have complete unit tests for uploading and retrying.  This checkin gets things ready to write those unit tests.
> Large files: preparation

- Makefile
- b2/b2.py
- b2/progress.py
- b2/raw_simulator.py
- b2/utils.py
- pre-commit.sh
- test/test_bucket.py
- test/test_utils.py
- test_b2_command_line.py
This is not finished - many lines of code which retrieve and pass token must still be modified
> Add automatic reauthorization and B2Session layer

- b2/bucket.py
- b2/progress.py
- b2/raw_api.py
- b2/raw_simulator.py
- test/test_bucket.py
I found a couple bugs when I tried uploading to the staging servers at Backblaze.
> Fix upload large files

- .travis.yml
- b2/console_tool.py
- b2/raw_api.py
- b2/raw_simulator.py
- pre-commit.sh
I'm going to try checking in account credentials that can be used to test B2RawApi.  As long as nobody abuses it, it will help complete the testing of the code.
> Tests for B2RawApi

- b2/thread_pool.py
- test/test_bucket.py
- test/test_thread_pool.py
I didn't find an obvious library to use, so I wrote a super-simple thread pool.
> Simple thread pool class.

- .travis.yml
- b2/api.py
- b2/b2http.py
- b2/bucket.py
- b2/console_tool.py
- b2/exception.py
- b2/raw_api.py
- pre-commit.sh
- setup.py
- test/test_b2http.py
- test/test_bucket.py
- test_b2_command_line.py
Not ready to merge yet, but would like comments.
> Tiny wrapper for requests

- .travis.yml
This will test the same environment that is present on OS X El Capitan.
> Run a python 2.7 build with six=1.4.1

- b2/account_info.py
- b2/bucket.py
- test/test_account_info.py
- test/test_bucket.py
- test_b2_command_line.py
Only one thread at a time will use an upload URL.
> Locking and upload URL management

- b2/b2http.py
- b2/raw_api.py
- test/test_b2http.py
The progress bar wasn't showing up, and big files were failing, because
the stream=True parameter was missing to the get call, so requests
was trying to buffer the entire file before returning.
> Fix bug downloading files.

- b2/console_tool.py
- b2/parse_args.py
- test/test_console_tool.py
- test/test_parse_args.py
Usage messages are more friendly now.
> Re-do argument parsing.

- b2/b2http.py
API now requires a seekable file-like object.
> Fix test_http.

- b2/bucket.py
- b2/exception.py
- b2/session.py
This is built on top of #123 which was contributed by @svonohr
> Finish reauthorization

- b2/api.py
I just found one additional bad auth token error. I hope that's now all of them.
> One more bad auth token error

- b2/api.py
- b2/b2http.py
- b2/bucket.py
- b2/console_tool.py
- b2/download_dest.py
- b2/exception.py
- b2/file_version.py
- b2/raw_api.py
- b2/raw_simulator.py
- b2/sync.py
- b2/utils.py
- test/test_console_tool.py
- test/test_sync.py
- test/test_utils.py
Sync is not done, but syncing up to B2 mostly works.  And there have been a lot of changes (almost all in sync.py), so it's a good time to merge in.
> Sync: checkpoint work

- b2/account_info.py
- b2/api.py
- b2/console_tool.py
- b2/exception.py
- setup.py
- test/test_account_info.py
- test_b2_command_line.py
> Use sqlite to store account info in .b2_account_info

- b2/bucket.py
Implemented resuming large file uploads as discussed in #137 
At the moment SHA1 hashes might be calculated more than once for individual parts, but I didn't want to change the structure of the classes to much. I've not done extensive testing, since my upload bandwidth doesn't allow this at the moment. I will test this some more tomorrow.
> Resuming large file uploads

- b2/console_tool.py
- b2/sync.py
- test/test_sync.py
Implements the feature requested in #150.
> Added support for excluding files from sync

- test_b2_command_line.py
This fix changes the integration test so that it matches the rouding behavior of the sync command.
> Fix rounding of modification time

- b2/console_tool.py
- b2/sync.py
- test/test_sync.py
As discussed in #151.
It's still missing tests for the new option.
> Option to ignore modification time

- b2/api.py
- b2/bucket.py
- b2/console_tool.py
- b2/download_dest.py
- b2/exception.py
- b2/file_version.py
- b2/progress.py
- b2/raw_api.py
- b2/raw_simulator.py
- b2/sync.py
- test/test_bucket.py
- test/test_console_tool.py
- test/test_sync.py
- Changed `download_file_by_id`/`download_file_by_name` so that they accept a progress listener
- Added unit tests to check progress for downloading files
- Added unit tests to verify that progress listeners are actually closed
> Progress listener refactoring

- b2/bucket.py
- b2/raw_simulator.py
- test/test_bucket.py
Also fixed issue with raw simulator taking `len()` of `None`.
> Added more ls unit tests

- b2/api.py
- b2/bucket.py
- b2/console_tool.py
- b2/download_dest.py
- b2/sync.py
- b2/utils.py
- test/test_account_info.py
- test/test_bucket.py
- test/test_console_tool.py
- test/test_sync.py
Fixed potentially dangerous exceptions and default parameters, documented a missing parameter, etc.
> Small fixes

- b2/sync.py
- test/test_sync.py
- test_b2_command_line.py
Fixes #149.
Still needs a warning message.
> Skip broken symlinks

- b2/bucket.py
- b2/console_tool.py
Elliott at Backblaze is doing some performance testing and wanted this option.  It may be useful to other people, too.
> Add --minPartSize option when uploading a single file.

- b2/sync.py
- pre-commit.sh
Add an assertion to help diagnose #190.
> Work on 190

- README.md
- b2/console_tool.py
My suggested changes for issue #228 
Defaults threads to a single one, and adds documentation explaining who will benefit from increasing.
> Adjust threads default, add documentation

- b2/console_tool.py
- b2/parse_args.py
- test/test_base.py
- test/test_console_tool.py
- test/test_parse_args.py
It first gets the file info, to acquire the file name, then
it deletes the version with the given ID.
> Add a command to delete a file given just the file ID.

- b2/exception.py
- test/test_exception.py
> Handle unicode in exception messages

- b2/console_tool.py
- b2/parse_args.py
- b2/sync/sync.py
- test/test_console_tool.py
- test/test_sync.py
Implemented most of #150 ("excluding files from sync") requests and including-override added. Note that it still lacks rsync-style (include|exclude)-from=FILE
> More sync options

- b2/api.py
- b2/bucket.py
- b2/download_dest.py
- b2/exception.py
- b2/raw_api.py
- b2/raw_simulator.py
- test/test_bucket.py
> Add optional range_ parameter to download_file_by_* (API level)

- b2/console_tool.py
- b2/sync/action.py
- b2/sync/sync.py
- test/test_console_tool.py
- test/test_sync.py
TODO: add test(s) to `test_b2_command_line.py`.
> Issue 188 add dry run to sync

- b2/sync/folder.py
- b2/sync/report.py
- test/test_sync.py
Inspired by @Telofy ([here](https://github.com/Backblaze/B2_Command_Line_Tool/issues/149#issuecomment-264288367))
> Add sync permission check

- README.md
As above.
And just to add - this new `--dryRun` switch works perfectly!
Pete
> Included sync command --dryRun switch in README.md

- b2/console_tool.py
- b2/raw_api.py
- b2/sync/action.py
- b2/sync/folder.py
- test/test_console_tool.py
- test_b2_command_line.py
> Always set src_last_modified_millis in upload_file command.

- README.md
- b2/console_tool.py
- test/test_console_tool.py
Add a command to display the account info stored in the sqlite database.
> Show account info

- b2/sync/sync.py
- test/test_sync.py
> Limit the number of sync actions queued in memory.

- contrib/color-b2-logs.sh
This way Codacy can run static code analysis on the script.
> Add shebang to a contrib script

- README.md
> Fix space in badge urls and reposition them

- b2/api.py
- b2/console_tool.py
- b2/raw_simulator.py
- test/test_console_tool.py
This creates an URL with a build-in auth token for downloading a file from a private bucket.
> New get-download-url-with-auth command

- b2/download_dest.py
- b2/progress.py
- b2/raw_api.py
- b2/raw_simulator.py
- pre-commit.sh
- test/test_bucket.py
- test/test_console_tool.py
- test/test_download_dest.py
> Set mod time when downloading files

- README.md
- b2/api.py
- b2/bucket.py
- b2/console_tool.py
- b2/raw_api.py
- b2/raw_simulator.py
- test/test_console_tool.py
Added CORS rules to create/update bucket implementations
Added lifecycle rules to bucket
Fixed some typos
Updated tests and usage commands(pre-commit.sh runs and passes)
> Added support for 'Coming Soon: CORS rules'

- .travis.yml
- b2/download_dest.py
- b2/sync/folder.py
- b2/utils.py
- requirements.txt
- setup.py
- test_b2_command_line.py
Mainly this is a fix for https://github.com/Backblaze/B2_Command_Line_Tool/issues/265 and https://github.com/Backblaze/B2_Command_Line_Tool/issues/397, with some other bonuses thrown in.  Comments welcome.
> Fix Windows integration tests, long Windows paths, and stale sync files

- .travis.yml
- requirements.txt
- setup.py
https://github.com/crsmithdev/arrow/issues/517
> Fix build broken by arrow 0.12.1 and 3.7

- b2/console_tool.py
- test/test_console_tool.py
> Add --recursive option to ls command

- MANIFEST.in
> Include LICENSE file in the source tarball. Fixes #433

- b2/account_info/abstract.py
tested by logging in to dev environment and production environment.
> update baseUrl for dev environment.

- .travis.yml
- b2/b2http.py
- requirements-test.txt
Creating pull request before done to check the build.
> Fix the build.

- b2/console_tool.py
- test/test_console_tool.py
> Add information about required capabilities to doc string for each command.

- b2/account_info/abstract.py
- b2/api.py
- b2/console_tool.py
- b2/exception.py
- b2/raw_simulator.py
- b2/session.py
- test/test_api.py
- test/test_console_tool.py
- test/test_session.py
A bunch of bug fixes an cleanup for application keys.
> App keys fixes

- b2/bucket.py
- b2/console_tool.py
- b2/download_dest.py
- b2/progress.py
- b2/transferer.py
- test/test_download_dest.py
created from https://github.com/Backblaze/B2_Command_Line_Tool/pull/480#discussion_r206868610
> Improve progress reporters closing

- b2/bucket.py
- b2/console_tool.py
- b2/download_dest.py
- b2/progress.py
- b2/transferer.py
- test/test_download_dest.py
This is based on top of #482 which should be merged before this one
> Faster downloads prework4

- README.md
- README.release.md
- requirements-setup.txt
> Add instructions on updating packages, including setuptools.

- requirements-setup.txt
> Add twine to the list of things to install for setup.

- b2/account_info/abstract.py
- b2/account_info/in_memory.py
- b2/account_info/sqlite_account_info.py
- b2/api.py
- b2/raw_simulator.py
- test/stub_account_info.py
- test/test_account_info.py
- test/test_api.py
> Fix reauthorizing with an application key

- b2/raw_simulator.py
- b2/transferer/parallel.py
- b2/transferer/transferer.py
- test/test_bucket.py
Resolves #450 and it's a final piece of it.
This PR is the key in the #450 effort, but refactoring of the existing codebase, fixing bugs and extensions of tools were already merged to master over the last couple of weeks in order to make the review more effective. Those other PRs include #463, #465, #476, #477, #479, #480, #486, #496, #501, #502 and #503.
> Faster downloads

- b2/console_tool.py
It needs to list files to know what to cancel.
> Update doc string for cancel-all-unfinished-large-files

- .travis.yml
- appveyor.yml
- setup.py
> remove python 2.6 dependency and update arrow version.

- README.md
> Correct README with regards to the 1.4.0 release

- .travis.yml
- ci/license_strategy.ini
- requirements-test.txt
Add liccheck in .travis.yml with license strategy for authorized licenses.
> Add liccheck in .travis.yml

- test/test_console_tool.py
Remove api version imports and fix test case
Fix test on python2.7
> Changes for migration to b2sdk-1.0.0

- README.md
- b2/console_tool.py
> Add prefix parameter support

- README.md
- b2/console_tool.py
- test_b2_command_line.py
Resolves #577. Credit goes to @meganekko, I only added a test to his #612.
> Add "make-friendly-url" command

- README.md
- b2/console_tool.py
- requirements.txt
- test/test_console_tool.py
> Add --environment for providing custom realm #642

- README.md
- b2/console_tool.py
> Remove --prefix from ls subcommand

- CHANGELOG.md
- b2/arg_parser.py
- b2/console_tool.py
- doc/source/index.rst
- requirements.txt
Preview:
https://b2-command-line-tool.readthedocs.io/en/doc-update/index.html
https://b2-command-line-tool.readthedocs.io/en/doc-update/subcommands/sync.html
> Doc update for sync

- CHANGELOG.md
- b2/console_tool.py
- test/integration/test_b2_command_line.py
- test/unit/test_console_tool.py
> SSE-B2 support

- CHANGELOG.md
- setup.py
> Exclude packages inside test*

- CHANGELOG.md
- test/integration/test_b2_command_line.py
replaces https://github.com/reef-technologies/B2_Command_Line_Tool/pull/66
> Integration test for sync within one bucket with different encryption

- CHANGELOG.md
- test/integration/test_b2_command_line.py
replaces https://github.com/reef-technologies/B2_Command_Line_Tool/pull/69
> Fixed breaking integration test case

- .github/workflows/ci.yml
- CHANGELOG.md
- b2.spec
- test/integration/test_b2_command_line.py
> Add zoneinfo to the windows bundle

- CHANGELOG.md
- README.md
Solves https://github.com/Backblaze/B2_Command_Line_Tool/issues/741 . Original wording of the change proposed by @philh7456
> Installation instructions corrected

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- noxfile.py
> Static binary for Linux

- .github/workflows/cd.yml
- CHANGELOG.md
- noxfile.py
> Sign Windows bundle

- .github/workflows/ci.yml
- CHANGELOG.md
```
./B2_Command_Line_Tool/CHANGELOG.md:59: bahaviour ==> behaviour
./B2_Command_Line_Tool/CHANGELOG.md:60: bahaviour ==> behaviour
./B2_Command_Line_Tool/CHANGELOG.md:220: capabilites ==> capabilities
```
> ci.yml: Discover typos with codespell

- CHANGELOG.md
- b2/console_tool.py
- b2/json_encoder.py
- requirements.txt
- test/integration/test_b2_command_line.py
- test/unit/test_console_tool.py
This is the same as `replication-monitoring` branch but rebased on latest upstream master and added few commits (--noProgress and test_replication_monitoring).
> Add replication-status command

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- b2/console_tool.py
- requirements-doc.txt
- requirements-license.txt
- requirements.txt
- test/unit/test_console_tool.py
> Prepare 3.7.0

- CHANGELOG.md
- b2/console_tool.py
- Also, additional parameters for printing were removed from rm command
> Clarification of parameters for ls/rm commands

- CHANGELOG.md
- test/integration/test_autocomplete.py
Increase TIMEOUT value in test_autocomplete.py to accommodate slower CI environments
> Increase TIMEOUT

- CHANGELOG.md
- b2/console_tool.py
- requirements.txt
- test/unit/test_console_tool.py
Support for cache control option when uploading a local file though CLI
> Support for cache control option when uploading a file

- .readthedocs.yml
- CHANGELOG.md
- noxfile.py
- requirements-doc.txt
- requirements-license.txt
- requirements.txt
* updated some doc-related deps & fixed rtd build
* disabled doc_cover as it errors out with new Sphinx and does not provide any value in B2 CLI
> update deps & fix the readthedocs build

- CHANGELOG.md
- README.md
- b2/console_tool.py
- test/integration/helpers.py
- test/integration/test_b2_command_line.py
- test/unit/console_tool/test_download_file.py
- test/unit/test_console_tool.py
Added ---quiet as a parameter to `download-file-by-id` and `download-file-by-name`.
> Aded --quiet parameter to download by file and id.

- CHANGELOG.md
- b2/console_tool.py
- test/integration/helpers.py
- test/unit/test_console_tool.py
> Fix stdout noise on auth breaking ls json output

- .github/workflows/ci.yml
- changelog.d/+add_header_options.added.md
- changelog.d/+cat.doc.md
- changelog.d/+checking-changelog-entries.infrastructure.md
- changelog.d/+fix_leaking_semaphores.fix.md
- changelog.d/+fix_leaking_semaphores.fixed.md
- changelog.d/+python3.12.infrastructure.md
- changelog.d/+remove_redundant_todo.infrastructure.md
- changelog.d/+skip_draft_step_in_releases.infrastructure.md
- noxfile.py
Also fixing all the towncrier checks in the current changelog.
This is a copy of a change made for `b2sdk`.
> Nox session for basic validation of changelog entries

- README.md
> installing from source instructions

- b2/_internal/_cli/b2args.py
- b2/_internal/console_tool.py
- changelog.d/+command-file-large.added.md
- changelog.d/+command-file-large.deprecated.md
- test/unit/test_console_tool.py
> Added file large subcommand

- b2/_internal/console_tool.py
- changelog.d/+with_auth_b2id_error.fixed.md
- test/unit/console_tool/test_get_url.py
> Display error message when using --with-auth for b2id urls

- noxfile.py
Reverts Backblaze/B2_Command_Line_Tool#1056
> Revert "Use SHA384withRSA for Windows signing"
