b2
Also clean up stale mappings when downloading a fresh list of bucket
names (previously only new entries were being added).
=> Reduce number of config writes when bucket name cache is updated

b2
Currently, the b2 tool, when creating a new `${HOME}/.b2_account_info` file uses the interactive shell's `umask` setting to set the permissions on the file. This update forces the file to be created as mode 600 - which would be the better setting on a shared-access system.
=> Update file-create to force mode 600

b2
Fix clear_account - fixes Backblaze/B2_Command_Line_Tool#8
Remove commented code
Use json.dump instead of json.dumps to write account info
Do not skip O_BINARY flag on Windows
=> Fix _write_file() not truncating the writing account info

b2
My use case includes uploading large files to B2 (100-200 GB) and I would prefer not to have to read the whole file purely to get the SHA1 checksum when I already have those sums locally during file creation.
=> Support external SHA1 sum

b2, test_b2_command_line.py
This allows scripts to easily parse the JSON that upload_file prints to stdout.
=> Add --quiet option to upload_file.

b2
This PR is WIP (created for easy early review). Please do not merge it before it is ready.
This will eventually implement #4.
Task list:
Unfinished items will be done in another PR
=> Library layer - first part

README.md, b2
Not the very cleanest of implementations. A few rough corners:
* Compares on file name and size only.
* ~~Doesn't preserve last modified timestamps.~~ *FIXED*
* ~~Re-uses other actions as helpers, which is non-optimal...~~ *FIXED*
* ~~Output is not understandable (each action outputs differently)~~ *FIXED*
* The `--delete` option doesn't work if multiple B2 file versions exists.
* Symlinks and other special files are handled as ordinary files.
The comparison should reuse the SHA-1 calculated during the upload, but it doesn't seem to be available via the API.
~~Most other issues above seem easy enough to address with a few refactorings here and there. But I won't embark on that unless this PR seems interesting to you.~~
=> Added new 'sync' action for easy local <-> remote copying

README.md, b2, test_b2_command_line.py
Running b2 under a low privileged user, such as user nobody, has problems with the credential file.
Typically uses such as these do not have a home directory which means that '~/.b2_account_info' will resolve to '/.b2_account_info'.  This in turn means that the user will require write access to the root directory which is bad.
The solution is to allow the name of the credential file to be overridden using an environment variable 'B2_ACCOUNT_INFO'.  If this variable does not exist, the name will default to '~/.b2_account_info'
Example:
export B2_ACCOUNT_INFO=/tmp/b2_credentials
b2 authorize_account ${ACCT_ID} ${ACCT_KEY}
Thus B2 will store its credentials in the file '/tmp/b2_credentials' rather than the root directory
=> Allow credential file name to be overridden

b2/b2.py
`b2 sync` gave server error on `file names must not contain '\\'` because pathnames on Windows uses backslashes which are kept as is when constructing the corresponding remote pathnames.
=> BUG FIX: b2 sync on Windows 

b2/b2.py
Just a quick commit to fix a typo in the documentation. :wink:
=> Fix typo in upload_file documentation

b2/thread_pool.py, test/test_thread_pool.py
I think that we'll need to have tasks be able to add tasks
to the queue.  This means that using the shutdown tokens
in join() won't work, because other tasks might get added
behind them.
So the join() method now uses Queue.join().  And there is a
separate shut_down() method that stops the threads after
all of the tasks have been completed.
=> Rethink ThreadPool class.

.travis.yml, README.md, b2/__init__.py, b2/thread_pool.py, setup.py, test/test_b2http.py
I give up trying to stay compatible.  The installation using the system Python on Macs will just have to be a little different.
=> Remove ugly workarounds cause by trying to be compatible with six==1.4.1

b2/bucket.py, b2/exception.py
Fixed some of the errors discussed here #7 
I also changed the InvalidAuthToken exception so that the client retries uploading after such an error. Without this I was still getting errors if I upload very small files and the auth token was invalid.
=> Fixed multiple InvalidAuthToken errors

b2/upload_source.py
For large files the whole SHA1 is never needed, but calculated anyway.
=> Calculate SHA1 hash only if needed

b2/utils.py, test/test_utils.py
Now that the maximum file size is 10TB, the limit of
10,000 parts per file matters when choosing a part size.
=> Fix part size decision for really large files.

.travis.yml
This should not cause any trouble unless we will have conflicting PRs
which target a non-master branch at some time. This never happened yet,
so we are going to cut our Travis usage in half until it does.
=> Prevent running Travis CI twice on each commit

b2/console_tool.py
Without this you get the following exception when interrupting the B2 CLI:
```
Interrupted.  Shutting down...
Traceback (most recent call last):
File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/sebi/Desktop/b2_compare/B2_Command_Line_Tool/b2/__main__.py", line 15, in <module>
main()
File "/home/sebi/Desktop/b2_compare/B2_Command_Line_Tool/b2/console_tool.py", line 877, in main
os._exit(exit_status)
TypeError: an integer is required (got type NoneType)
```
=> Return an error code on keyboard interrupts

b2/raw_simulator.py, test/test_console_tool.py
The raw simulator was missing the `get_file_info` command. Additionally some of the results returned do not match the B2 API specification. Note that I had to change some unit tests, but I believe their previous expected value was in fact wrong.
=> Fixed raw simulator

b2/account_info.py, test/test_account_info.py
Fix #171 
This will keep the database from being a bottleneck when
sync-ing lots of files.  And now that b2_get_upload_url
is a free call, it doesn't cost any money to use it when
uploading a single file; it just costs a little time.
=> Don't store bucket upload URLs is SQLite.

b2/account_info/abstract.py, b2/b2http.py, b2/raw_api.py
The support for the new domain went live today.  The old domain (with redirects) will continue to work for six months.
=> Change domain name for B2 service from backblaze.com to backblazeb2.com.

requirements.txt
We don't want to specify an exact version, because that increases the probability of incompatibilities with other packages.
=> Restore original requests requirement: >=2.9.1

b2/b2http.py, test/test_b2http.py
It turns out that `requests` only does connection pooling when you
create a Session object.  So now we do that.
Verified that it's reusing connections by enabling debug logging and
watching it run.
=> Enable connection pooling.

pre-commit.sh
I recently started using B2 and thought I would take a crack at helping improving this utility, but I stumbled across a few quirks in the `pre-commit.sh` script, so here's a bunch of fixes that you may or may not like. It's probably easiest to go through the commits one at a time to get the reason for each change.
A thing I have yet to figure out is how to invoke the `quick` option of skipping the integration tests, as it will always collide with how the branch to check against is specified. I was thinking of adding some proper parameter parsing with getopt, but thought it would be a bit much - at least without consulting you guys.
=> pre-commit.sh fixes

test_b2_command_line.py
This commit adds an integration test for `sync --dryRun`.
=> add command-line test for sync --dryRun

b2/progress.py
=> Don't use tqdm in Python versions prior to 2.7.  

b2/console_tool.py, b2/sync/report.py, test/test_console_tool.py, test/test_sync_report.py
I had some trouble in configuring my terminal improperly, so I was not able to test it. Is there a reliable way someone could recommend?
=> Avoid UnicodeEncodeError on improperly configured terminals

README.md, b2/console_tool.py, test/test_console_tool.py
=> Accept both hyphens and underscores in command names.

b2/sync/policy.py, test/test_policy.py
The mod time used for syncing comes from the user-defined src_last_modified_millis,
which isn't guaranteed to be in order.  So I removed the assertion that they are in order.
=> Fix #331: assertion failure when syncing

.travis.yml, b2/b2http.py
caught at
https://github.com/Backblaze/B2_Command_Line_Tool/issues/350#issuecomment-313848165
I am not catching the actual encountered error worrying about
incompatibility of exception wrappers across various versions of python
and `requests` library.
=> Improve error handling for socket.error that is not 'Broken Pipe'

README.md, b2/console_tool.py, b2/sync/policy.py, b2/sync/sync.py, test/test_sync.py, test_b2_command_line.py
Add `--compareThreshold` to allow deltas in file modTime or size comparisons. Also add `--verbose` for simple verbose (debug) logs to stdout.
=> Add --compareThreshold and --verbose

b2/console_tool.py, b2/raw_api.py, test/test_b2http.py, test/test_bucket.py, test/test_console_tool.py
This will fix build errors caused by YAPF changing it's mind about how code should be formatted.
=> Run the latest version of YAPF: 0.19.0

b2/raw_api.py
Fixes #377
I don't think a test is really needed since it's checked by this line:
```python
if bytes_read != desired_length:
raise TruncatedOutput(bytes_read, desired_length)
```
=> Fixed off by one issue

b2/raw_api.py
Starting in November, 2017, some new bucket types will be added, and
the default will be to exclude them from the list of buckets.  The CLI
should show all the buckets.
=> Adapt to new b2_list_buckets API by explicitly request all buckets.

.travis.yml
It broke because travis went to a new version of python,
and the symlink to the system python from inside jython
broke.  In this case, we don't want to use the cached
jython installation.
If the cached jython won't run, it will be removed and
reinstalled.
=> Fix jython build.

.gitignore, b2/console_tool.py, test/test_console_tool.py
- Added --showSize to get-bucket. Introduces two new fields, fileCount and totalSize, that represent the count of files and the aggregate size of all files, respectively.
- Omission of --showSize results in the original behavior.
- Added venv to .gitignore.
Additional documentation is available in a comment on #404.
=> Implemented #404.

b2/console_tool.py, test/test_console_tool.py
- Improved documentation to describe behavior with respect to hidden files, versions, and hierarchical structures.
- Renamed test_get_bucket_show_size() to test_get_bucket_one_item_show_size().
- Added test_get_bucket_with_versions() (to check behavior wrt to multiple versions).
- Added test_get_bucket_with_folders() (to check behavior wrt to folders).
- Added test_get_bucket_with_hidden() (to check behavior wrt to hidden files).
- Added test_get_bucket_complex() (to check everything together).
All tests pass.
=> Added more unit tests for get-bucket --showSize.

Makefile, README.md, b2/b2http.py, b2/exception.py, b2/raw_api.py, pre-commit.sh, requirements-test.txt, setup.cfg, test/test_base.py, test/test_raw_api.py
This solves Issue #362 by checking filenames and halting if it finds an unusable filename.  (We can open another issue for what the behavior should be in this case.)
It raises an UnusableFilename exception with appropriate detailed message for filenames that don't meet the rules.
If the problem with a filename is that it has a character code < 32, it includes the offending filename in the exception that it raises, with a "\x00" style hex code in place of the unprintable character(s).
There is a positive and negative unit test for each file rule.
=> Reject unusable filenames early (before the server does).

test/test_sync.py
This PR fixes the relevant test so it behaves differently based on the file access permissions the current user running the test has. As discussed on the issue, it does **not** change `b2/utils.py` anymore as the behaviour there is as intended. If this PR is merged, it closes #427.
N.B.: This time I did run the `./pre-commit.sh` script and it marked:
```text
ALL OK
231.96 real        51.38 user        13.45 sys
integration tests passed
```
There were no changes to actual source code though, which I then committed to create this PR.
=> Fixes #427

appveyor.yml
Use python names from appveyor web site.
Exclude 2.6, which doesn't work.
=> Update appveyor build matrix

b2/exception.py
Currently this return code gets translated into an UnknownError exception which is not very helpful
=> Translate 404/not_found of get_file_info into FileNotPresent exception

README.md, b2/api.py, b2/console_tool.py, b2/raw_simulator.py, b2/sync/folder.py, test/test_console_tool.py, test_b2_command_line.py
Added the Create, Delete and List Key API's (not yet live) to the command availability.
Add test cases and some local checks in test_console_tool.py.
TODO: add functional testing in test_b2_command_line.py
Also fixed the issue we saw where the timestamp in milliseconds was returned differently for 
sync because we round in the unit tests, and not in sync (we no longer round), which we think
happened because the mac OSX changed the modified timestamp for files.
=> Adding support for Application Key API's

setup.py
setup.py excludes certain packages from deployment, including `tests`. However the test package in b2 is called `test` not `tests` (no s).
=> The testing package is called test, not tests

.travis.yml, setup.py
setuptools dropped support for 3.3 and refuses to
install anything in 3.3, so we're not able to run tests for it.
Also, stop claiming to support 3.3.  "If it's not tested, it doesn't work."
For some reason, setuptools does still support 2.6, which
hasn't had any releases since 2013.  I'm not taking that out
yet.
=> Fix #456 by dropping support for Python 3.3

setup.py
Fixes #460
This prettifies the package description on PyPI.
Gives a harmless warning in setuptools pre 40.x.
=> Add content type 'text/markdown' for the package long description

b2/sync/policy.py
PEP 479 changed behavior so that StopIteration does not bubble out of a generator.
Luckily the affected generators can just return immediately instead.
=> fix tests with Python 3.7

b2/console_tool.py, b2/raw_api.py, pre-commit.sh
There were three problems:
1. The download authorization with file prefix did not match the file being downloaded.
2. The bucket revision test was too picky.  The only promise that the service makes is that updates to a bucket increase the revision number.
3. `pre-commit.sh` was not detecting errors from the `raw_api_test`
=> Fix raw_api_test

b2/api.py, b2/console_tool.py, b2/exception.py, test/test_console_tool.py, test_b2_command_line.py
This is the fix for allowing us to make the CLI calls which require list buckets specifically when we have an application key that is restricted to a bucket.
=> List Bucket from allowed field only (if specified)

test_b2_command_line.py
For security reasons, 401 responses now have less-informative
messages.  This updates the test to match.
=> Update tests to match new error messages from the service.

b2/console_tool.py
It's now clearer about how to use master application keys vs. normal application keys.
Partial fix for #475
=> Update doc for authorize-account.

b2/bucket.py, b2/download_dest.py, b2/progress.py
This is needed because soon we read a part of the file from the drive after it's downloaded, to finish hashing it. Without this, progress showed more than 100%.
=> Separate progress listeners to read and write

contrib/bash_completion/b2
`have` is [deprecated](https://github.com/scop/bash-completion/blob/4d88339928aa064a567d5feb40694dfd24a274c5/bash_completion#L114) and gets unset at the end of
[bash_completion](https://github.com/scop/bash-completion/blob/4d88339928aa064a567d5feb40694dfd24a274c5/bash_completion#L2103) which can cause issues in certain situations
(specifically when running bash_completion on NixOS - because
the script is evaluated at the [start](https://github.com/NixOS/nixpkgs/blob/80b6513fbf5789ff0208c19a89bae49df2b503ad/nixos/modules/programs/bash/bash.nix#L22) but can't finish properly
because `have` is already unset at that point).
=> Use `_have` instead of `have` for bash completion

b2/console_tool.py
Couple of misspellings in `console_tool.py` help text and one comment.
=> fix minor typos in console tool help / comments

requirements-setup.txt
The push to PyPI is done in Python 3, so it's not needed.
=> Build fix: Do not depend on twine in 2.6.

b2/console_tool.py
The B2 API requires the file name when deleting a file.  When the name
is not provided on the command line, the command-line tool needs to
get the name, which requires readFiles capability.
=> Update doc string for delete-file-version.

README.md, b2/console_tool.py, b2/sync/folder.py, b2/sync/report.py, b2/sync/scan_policies.py, test/test_bucket.py, test/test_console_tool.py, test/test_raw_api.py, test/test_sync.py, test_b2_command_line.py
Opening this for comments -- I haven't visited this codebase in a while -- feedback on this approach is welcome and encouraged.
At first I thought of moving this into the `ScanPoliciesManager` routines, but since it affects both files and directories I elected to place the check in `LocalFolder._walk_relative_paths`.
```bash
zackse@goyeto# mkdir /tmp/symlink-test
zackse@goyeto# cd /tmp/symlink-test
zackse@goyeto# echo hello > hello
zackse@goyeto# ln -s hello hellolink
zackse@goyeto# mkdir adir
zackse@goyeto# echo hello > adir/hello2
zackse@goyeto# ln -s adir adirlink
zackse@goyeto# find -ls
126882253    0 drwxr-xr-x   6 zackse   wheel         204 Sep 20 13:18 .
126882256    0 drwxr-xr-x   3 zackse   wheel         102 Sep 20 13:18 ./adir
126882257    4 -rw-r--r--   1 zackse   wheel …
```
=> #390 Exclude symlinks from backup

b2/api.py
Bucket names are case-insensitive, so the assertion that the bucket
name coming back from the service matches should be case-insensitive.
=> Fix assertion on bucket name.

README.md, b2/console_tool.py, test/test_console_tool.py
User can now also optionally provide application key ID and application key using environment variables B2_APPLICATION_KEY_ID and B2_APPLICATION_KEY respectively.
=> Accept authorize-account arguments via environment

setup.cfg
MacOS seems to be very slow sometimes on TravisCI.
=> Fix timeouts in tests on Travis Mac OS

CHANGELOG.md, b2/console_tool.py
* Update for Backblaze/b2-sdk-python#165 in ``Sync``
* Fix name of parameters in ``CreateKey``
* Fix reStructuredText bulletlist in ``ListKeys``
=> Update the docs

.github/workflows/cd.yml, .github/workflows/ci.yml, CHANGELOG.md, noxfile.py
- Use python version from the container in CD
- Update the changelog
CD uses python container. See lined issue for details.
Closes #750
=> Fix for static linking of Linux binary

noxfile.py
Staticx doesn't work with pyinstaller bundle created from CPython installed by pyenv
=> Add NO_STATICX env flag for nox

CHANGELOG.md, b2/arg_parser.py
- Fallback to ascii decoder in case locales are not properly set
- Update the changelog
- Format the code
Fixes #755
Fixes #766
=> Fallback to ascii decoder in case locales are not properly set

CHANGELOG.md, b2/arg_parser.py, requirements.txt
Add some code that allows for arrow > 1.0 so that we can stop
restricting this for users relying on distribution packages. This code
handles the divergent behaviour of arrow on the 1.x and 0.x branches.
Related-to https://github.com/Backblaze/b2-sdk-python/issues/201
Unblocks https://github.com/Backblaze/b2-sdk-python/pull/204
Closes https://github.com/Backblaze/B2_Command_Line_Tool/issues/687
=> Allow for arrow >= 1.0.2

CHANGELOG.md, noxfile.py, test/integration/test_b2_command_line.py, test/unit/test_console_tool.py
This is a fix for the `test_keys` unit tests, which started failing after commit [043b919](https://github.com/Backblaze/b2-sdk-python/commit/043b919de9f43ca88f690f695631fd354b02a32f) (_Fix B2Api.get_key() returning wrong key if `key_id` is incorrect_) was added to b2sdk.
=> Fix failing test_keys unit test

CHANGELOG.md, test/integration/test_b2_command_line.py
Displaying the "source_encryption_mode" field in replication monitoring does not need any changes, the b2 sdk change is picked up automatically. Tests need to be adjusted however, and this PR fixes it.
=> Replication monitoring: update tests to use new source_encryption_mode field

.github/workflows/ci.yml, CHANGELOG.md, b2/console_tool.py, noxfile.py
In Python `3.11` `argparse` `add_parser` doesn't allow registering the same name/alias multiple times. Multiple registration was used to ensure that we have both name and alias in class registry. By removing multiple registration and ensuring that class is assigned to the parser, we no longer need to fetch objects from registry during run – thus removing the issue entirely.
=> Fetching command class from parsed arguments instead of registry

.github/workflows/cd.yml, .github/workflows/ci.yml, CHANGELOG.md, noxfile.py, requirements.txt, test/unit/test_console_tool.py
- Each release file receives a `_hashes.txt` file that contains several hex digests of the file.
Piggyback:
- upgraded github workflows versions when applicable to the latest one
- using `GITHUB_OUTPUT` instead of deprecated `set-output`
- limited `b2sdk` `requirements.txt` version to `2.0.0`
- fixes tests for `b2sdk` `1.19.0`, made it the baseline required version
=> Hashes of releases added

CHANGELOG.md, test/integration/test_autocomplete.py
Before this IF tested b2 package was not installed test will fail 100%.
What is even worse, if there was any other b2 version installed, this test would have run that one instead of the one from the local working directory.
=> fix integration tests erroring out when tested b2 package was not installed

CHANGELOG.md, b2/console_tool.py, test/unit/test_console_tool.py
This pull request fixes race condition and reporter count update problems as reported in https://github.com/Backblaze/B2_Command_Line_Tool/issues/872.
The first fix is to ensure update_total is called before a task is submitted to the executor. This change was necessary to prevent a race condition in which the task could potentially finish before update_total is called, leading to unpredictable test outcomes. By ensuring that update_total is called before the task submission, we guarantee that the total count is always accurate at the time of task execution.
The second fix improves the updating of the reporter count. Initially, the reporter count was being updated before the future result was obtained, which could lead to inaccurate count values if the future result returned an exception. …
=> Fix Fast rm sometimes fails unit tests #872

CHANGELOG.md, b2/arg_parser.py, test/unit/test_arg_parser.py
This PR addresses an issue (https://github.com/Backblaze/B2_Command_Line_Tool/issues/888) where executing b2 --help in a non-UTF8 terminal would raise a UnicodeEncodeError due to improper handling of Unicode characters. The fix ensures that Unicode characters are correctly encoded irrespective of the terminal's locale. Unit tests have been added to prevent this issue from reoccurring in future releases.
=> Fix UnicodeEncodeError in Non-UTF8 Terminals

CHANGELOG.md, b2/console_tool.py
Fixes something we missed in  #924 
This **may** fix Mac integration tests errors we have been seeing as well.
=> set `--noProgress` implicitly if `--quiet` was selected

.github/workflows/push_docker.yml, CHANGELOG.md
- add `linux/arm64` as a platform which is the default for running docker images on Apple Silicon (tested on https://hub.docker.com/r/yedpodtrzitko/b2/ )
- remove B2 env. variables as these are unused in given action file
=> feat: build docker image for arm architecture

CHANGELOG.md, README.md
without `-i` it fails with very ugly error on linux as AFAIK can tell it is basically /dev/null without it
=> fix docker cmd example so it works properly on Linux

changelog.d/952.fixed.md, pyproject.toml
=> fix: make pyproject.toml content viable for pip install

CHANGELOG.md, b2/console_tool.py, requirements.txt, test/integration/test_b2_command_line.py, test/unit/console_tool/test_upload_file.py
Adds --expires, --content-disposition, --content-encoding, --content-language options to subcommands upload-file, upload-unbound-stream, copy-file-by-id.
=> Add CLI arguments to set Expire, Content-Language, Content-Disposition, Content-Encoding

CONTRIBUTING.md, README.md, b2/_cli/argcompleters.py, b2/_cli/b2args.py, b2/_utils/python_compat.py, b2/_utils/uri.py, b2/arg_parser.py, b2/console_tool.py, b2/json_encoder.py, changelog.d/+b2_uri_cmds.added.md, changelog.d/+b2_uri_cmds.deprecated.md, changelog.d/+cat.doc.md, doc/source/subcommands/cat.rst, doc/source/subcommands/download_file.rst, doc/source/subcommands/file_info.rst, doc/source/subcommands/get_url.rst, test/integration/test_autocomplete.py, test/integration/test_b2_command_line.py, test/unit/_utils/test_uri.py, test/unit/console_tool/conftest.py, test/unit/console_tool/test_download_file.py, test/unit/console_tool/test_file_info.py, test/unit/console_tool/test_get_url.py, test/unit/console_tool/test_help.py, test/unit/test_arg_parser.py, test/unit/test_console_tool.py
* Add `download-file`, `file-info` and `get-url` commands using new B2 URI syntax allowing for referring to file-like objects by their bucket&name or ID.
* Deprecated `download-file-by-id` and `download-file-by-name`, use `download-file` instead.
* Deprecated `get-file-info`, use `file-info` instead.
* Deprecated `make-url` and `make-friendly-url`, use `get-url` instead.
Deprecation means here that stderr WARNING will be printed for those commands upon use.
=> B2 URI commands

b2/console_tool.py, changelog.d/+fix-list-formatting.doc.md
Lists are not properly rendered without the additional linebreak, cf. https://b2-command-line-tool.readthedocs.io/en/v3.13.1/#overview
=> fix Markdown formatting

.github/workflows/push_docker.yml, changelog.d/+docker_py312.changed.md, changelog.d/+loosen_platformdirs.fixed.md, requirements.txt
* fixes CD docker build fail https://github.com/Backblaze/B2_Command_Line_Tool/actions/runs/7119640521/job/19385199673
* it seems poetry requires just released platformdirs v3.11 - for us this makes no difference, so I loosened this requirement as it is pretty popular piece of software
=> Change docker py312 + loosen platformdirs requirement

b2/console_tool.py, changelog.d/+downloaded-file-name.added.md, requirements.txt, test/unit/console_tool/test_download_file.py, test/unit/test_console_tool.py
Two places are updated:
- "Output file path" is added to the download info printing
- Output file name is presented on the progress bar
=> Printing the output path for the downloaded object

b2/_internal/console_tool.py, changelog.d/+authorize-account-output.added.md, test/unit/console_tool/test_authorize_account.py, test/unit/test_console_tool.py
Currently, the `b2 authorize-account` command does not output anything if the command is successful. To get the account info, you need to invoke another command (`b2 get-account-info`).
This PR prints the account info after the `b2 authorize-account` command. The output is similar to `b2 get-account-info`.
=> Print account info on `b2 authorize-account`

b2/_internal/_utils/uri.py, changelog.d/+b2uri-special-characters.fixed.md, test/unit/_utils/test_uri.py
To support wildcards in `ls` and `rm` URIs, this PR prepares b2uri parsing to account for `?` and `#` characters in URI paths.
=> Fix b2uri wildcard

b2/_internal/console_tool.py, changelog.d/+fix-rm-non-recursive.fixed.md, test/unit/test_console_tool.py
Running `b2 rm myBucket folder` should delete everything directly in `folder` but, should not delete in files in the the subdirectories of `folder`.
The bug makes the above command delete the first file from every subdirectory under `folder`.
=> Fix non-recursive rm deleting files in subdirectories

b2/_internal/_cli/b2api.py, b2/_internal/_cli/b2args.py, b2/_internal/b2v3/registry.py, b2/_internal/console_tool.py, changelog.d/+not-saving-auth-data-when-env-vars.fixed.md, test/integration/conftest.py, test/integration/helpers.py, test/integration/test_b2_command_line.py, test/unit/console_tool/test_download_file.py, test/unit/console_tool/test_upload_file.py, test/unit/test_console_tool.py, test/unit/test_represent_file_metadata.py
Re https://github.com/Backblaze/B2_Command_Line_Tool/issues/894
**Current behavior:**
When users use env vars for authenticating in B2, those credentials are stored in `~/.b2_account_info` file which is unexpected by users and exposes B2 secrets to everyone who can read the file.
**New behavior (CLI >=v4 only):**
If user uses env vars for authentication, console tool uses `InMemoryAccountInfo` for storing account info and `InMemoryCache` for caching data.
Exception: when user calls `authorize-account` or `clear-account` commands, they store (or clear) credentials *on disk* even if "env vars authorization" is used.
--
This PR also removes `b2_api` parameter from `ConsoleTool` class init method. It was used only in tests and allowed passing mocked `B2Api` instance, however it added …
=> Use `InMemoryAccountInfo` when using env vars for authentication

.github/workflows/ci.yml
Workaround for https://github.com/actions/setup-python/issues/696
=> fix GHA CI by using old macos for old python versions

README.md, b2/_internal/b2v3/registry.py, b2/_internal/b2v3/rm.py, b2/_internal/b2v4/__init__.py, b2/_internal/b2v4/__main__.py, b2/_internal/b2v4/registry.py, changelog.d/+apiver-v4.changed.md, pyproject.toml, test/integration/conftest.py, test/unit/test_console_tool.py
=> Renamed _b2v4 to b2v4, b2 points to b2v4

b2/_internal/_cli/const.py, b2/_internal/console_tool.py, changelog.d/+logging-encoding.fixed.md, docker/Dockerfile.template
Enable `backslashreplace` escaping in logging. Especially needed if for some reason Python decides to use `ascii` encoding as the default one.
Set `B2_CLI_DOCKER=1` env when running in Docker, and log a debug message if it's set.
=> Escape invalid unicode in logging, log more locale info

b2/_internal/console_tool.py, changelog.d/1071.fixed.md
BrokenPipeError happens when a cli output has been piped to another program, which likely closes the pipe early because it already received enough data for it's use case (e.g. `head`)
=> Avoid failing on BrokenPipeError when running commands

.gitignore, changelog.d/+autocomplete_tests.infrastructure.md, test/integration/conftest.py, test/integration/helpers.py, test/integration/persistent_bucket.py, test/integration/test_autocomplete.py
- **Increase terminal window size for autocomplete integration tests**
- **Add .venv to gitignore**
- **Fix lint issues**
=> Fix pexpect issue in integration tests, lint

changelog.d/1088.infrastructure.md, pdm.lock, pyproject.toml, test/integration/helpers.py, test/integration/persistent_bucket.py
This PR replaces the backoff library with tenacity for improved retry functionality and better maintenance.
=> Fix #1088: Replace backoff with tenacity

.github/workflows/cd.yml, changelog.d/+keylocker_migration.changed.md, noxfile.py
Update the GitHub actions in `cd.yml` to use DigiCert's [KeyLocker](https://docs.digicert.com/en/digicert-keylocker.html) and cloud based signing solutions for increased code signing certificate security.
=> Update Windows code signing to use KeyLocker

changelog.d/1101.fixed.md, pdm.lock, pyproject.toml
Some parts of the docutils were deprecated in 0.22.x that
the dependent rst2ansi package relied upon
=> Pin docutils version

b2/_internal/_utils/uri.py, changelog.d/1090.fixed.md, test/unit/_utils/test_uri.py, test/unit/console_tool/test_download_file.py
Fix #1090 
Previously, `urllib.parse.urlsplit` was being used to parse the URL. This breaks the filename/path across path, query and fragment introducing various cases where the filename changes from the user-intended filename like:
- files starting with `/`
- files ending with `?` or `#`
Replacing it with a simpler parser which only returns `(scheme, netloc, path)` solves these issues.
=> Replace urlsplit with a new parser
